name: Docker Image CI

on:
  push:
    branches: [cicd]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
          login-server: iamrepo.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    - run: |
          docker build . -t iamrepo.azurecr.io/iamrepo:latest
          docker push iamrepo.azurecr.io/iamrepo:latest
